logger:
  level: "DEBUG"
console:
  username: "<CONSOLE_USERNAME>"             
  password: "<CONSOLE_PASSWORD>" 
session:
  token_expiry_sec: 3600
  refresh_token_expiry_sec: 86400
social:
  apple:
    bundle_id: "com.example.giftGrab"