# https://heroiclabs.com/docs/nakama/getting-started/configuration/

logger:
  level: "DEBUG"
session:
    token_expiry_sec: 3600          # Main token expires in 1 hour
    refresh_token_expiry_sec: 86400 # Refresh token expires in 24 hours